require 'filipinomemes/core_ext/kernel'
require 'filipinomemes/core_ext/string'
require 'filipinomemes/core_ext/array'
require 'filipinomemes/core_ext/enumerator'
require 'filipinomemes/core_ext/integer'
require 'filipinomemes/core_ext/range'
require 'filipinomemes/core_ext/class'
require 'filipinomemes/core_ext/module'
